# Generated by Django 4.2.10 on 2024-02-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
    ]
