# Generated by Django 4.2.11 on 2024-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_booking_remove_form_category_remove_form_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
