# Generated by Django 4.2.11 on 2024-04-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
