# Generated by Django 4.2.11 on 2024-04-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_booking'),
    ]

    operations = [

    ]
