# Generated by Django 4.2.11 on 2024-04-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_form_category_remove_form_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='category',
        ),
        migrations.RemoveField(
            model_name='form',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='response',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='response_to',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
    ]
