# Generated by Django 4.2.11 on 2024-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
