# Generated by Django 4.2.11 on 2024-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
