# Generated by Django 4.2.11 on 2024-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_booking_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
