# Generated by Django 4.2.11 on 2024-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_remove_booking_paymentref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
